### ISSUE TITLE
Can this be used on the latest version of Ionic

### ISSUE THREAD

**Issue by nikmartin** [shangyilim/ionic2-date-picker#19]
You can't inject ViewController into an ionic lazy loaded @Page @Component, so when I try to use this component in the latest version of Ionic, I get 'No Provider for ViewController errors. Do you know if this component work on the latest Ionic?

**Comment by shangyilim** [comment]
The last time i checked i was able to use it with ionic 3. Can you provide a sample code of how you used the date picker as well as the version of ionic you are using?

**Comment by nikmartin** [comment]
I got past that error, and now get:

```
Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /home/nmartin/Projects/GHA/gha-app/node_modules/ionic2-date-picker/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /home/nmartin/Projects/GHA/gha-app/node_modules/ionic2-date-picker/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /home/nmartin/Projects/GHA/gha-app/node_modules/ionic2-date-picker/node_modules/@angular/core/core.d.ts
    at syntaxError (/home/nmartin/Projects/GHA/gha-app/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/home/nmartin/Projects/GHA/gha-app/node_modules/@angular/compiler/bundles/compiler.umd.js:25118:23)
    at StaticReflector.simplify (/home/nmartin/Projects/GHA/gha-app/node_modules/@angular/compiler/bundles/compiler.umd.js:25130:13)
    at StaticReflector.annotations (/home/nmartin/Projects/GHA/gha-app/node_modules/@angular/compiler/bundles/compiler.umd.js:24558:41)
    at NgModuleResolver.resolve (/home/nmartin/Projects/GHA/gha-app/node_modules/@angular/compiler/bundles/compiler.umd.js:14896:70)
    at CompileMetadataResolver.getNgModuleMetadata (/home/nmartin/Projects/GHA/gha-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15551:60)
    at addNgModule (/home/nmartin/Projects/GHA/gha-app/node_modules/@angular/compiler/bundles/compiler.umd.js:24408:58)
    at /home/nmartin/Projects/GHA/gha-app/node_modules/@angular/compiler/bundles/compiler.umd.js:24419:14
    at Array.forEach (<anonymous>)
    at _createNgModules (/home/nmartin/Projects/GHA/gha-app/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:26)

```
when trying to build an ionic project with --prod flag
